# action.yml
name: 'Typilus Suggest'
description: 'Suggest Python Type Annotations'
branding:
    icon: box
    color: gray-dark
inputs:
  path:
    description: 'File or directory to run Typilus on.'
    required: false
    default: '.'
outputs:
  output:
    description: 'A list of suggestions.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
