# action.yml
name: 'Typilus: Suggest Python Type Annotations'
description: 'Suggest Likely Python Type Annotations'
branding:
    icon: box
    color: gray-dark
inputs:
  path:
    description: 'File or directory to run Typilus on.'
    required: false
    default: '.'
outputs:
  output:
    description: 'Makes suggeted edits to the pull requests for adding Python Type annotations.'
runs:
  using: 'docker'
  # Once debugging is done, replace with docker.pkg.github.com/typilus/typilus-action/actionenv:latest
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
